import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Twiter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://img.icons8.com/color/344/twitter--v1.png" />
      </Head>

      <main className='flex min-h-screen mx-auto'>
      {/* sidebar */}

      <Sidebar></Sidebar>

      {/* feed */}

      <Feed/>

      {/* widgets */}

      <Widgets/>

      {/* modal */}
      </main>
      

    </div>
  )
}
