import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Twiter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex min-h-screen mx-auto'>
      {/* sidebar */}

      <Sidebar></Sidebar>

      {/* feed */}

      <Feed/>

      {/* widgets */}


      {/* modal */}
      </main>
      

    </div>
  )
}
